version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: gbcoupons-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=gbcoupons
        - MYSQL_DATABASE=gbcoupons
        - MYSQL_USER=gbcoupons
        - MYSQL_PASSWORD=gbcoupons
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: gbcoupons-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: gbcoupons-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

